### ISSUE TITLE
aria2.getVersion not working

### ISSUE THREAD

**Issue by fengye** [sonnyp/aria2.js#13]
I wrote a simple test.js script:
```javascript
'use strict';

var Aria2 = require('aria2'),
  aria2Options = {host: 'localhost', port: 6800, secure: false},
  aria2 = new Aria2(aria2Options);

aria2.open();
aria2.send('getVersion', function(err, res) {
  console.log('version: ', err || res);
});

```

And another script using different calling convention:
```javascript
'use strict';

var Aria2 = require('aria2'),
  aria2Options = {host: 'localhost', port: 6800, secure: false},
  aria2 = new Aria2(aria2Options);

aria2.open();
aria2.getVersion(function(err, res) {
  console.log('version: ', err || res);
});

```

They both get errors:
```
/home/feng_ye/node_modules/aria2/Aria2.js:99
    if (m.id !== undefined) {
         ^
TypeError: Cannot read property 'id' of undefined
    at Aria2._onmessage (/home/feng_ye/node_modules/aria2/Aria2.js:99:10)
    at /home/feng_ye/node_modules/aria2/Aria2.js:55:12
    at response.onend (/home/feng_ye/node_modules/aria2/node_modules/httpclient/lib/index.js:41:9)
    at IncomingMessage.<anonymous> (/home/feng_ye/node_modules/aria2/node_modules/httpclient/lib/node.js:81:16)
    at IncomingMessage.g (events.js:180:16)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)
```

I think at least the send() method was working in version 0.0.6.

The aria2.js version is 1.0.1. 
The node.js version is v0.10.37. 
System is Ubuntu 12.04. 
aria2c was started as: ```aria2c --enable-rpc --rpc-listen-all=true --rpc-allow-origin-all```

**Comment by edtechd** [comment]
Hey, please try this patch

https://github.com/edtechd/aria2.js/commit/eb568babd5e48726d6e47b71f5c6093085c7f34d

**Comment by fengye** [comment]
edtechd: Well I didn't test thoroughly but in this case it worked for me! Thanks for the patch, any pull request so that I can install it using npm?

**Comment by sonnyp** [comment]
There is an issue with the http transport indeed, will fix soon.
@fengye meanwhile, wait for the open event before sending request (so that websocket will be used)

```javascript
'use strict';

var Aria2 = require('./Aria2'),
  aria2Options = {host: 'localhost', port: 6800, secure: false},
  aria2 = new Aria2(aria2Options);

aria2.open(function() {
  aria2.send('getVersion', function(err, res) {
    console.log('version: ', err || res);
  });
});
```

**Comment by FlyersWeb** [comment]
+1

**Comment by sonnyp** [comment]
fixed in https://github.com/sonnyp/aria2.js/pull/19
