### ISSUE TITLE
how to use this in browser

### ISSUE THREAD

**Issue by gautamkrishnar** [sonnyp/aria2.js#45]
I cant see any specific builds for browsers. I tried using browserifly but it didn't worked. Can you guys let me know how can we use this for web browsers.

**Comment by sonnyp** [comment]
>  I tried using browserifly but it didn't worked

Browserify works fine with aria2.js, double check your configuration / usage .

We used to have the browser bundle shipped with aria2.js . I would be open to re-introduce it. I just assumed everybody used templates and build systems nowadays when writing web apps. What is your use case?

**Comment by gautamkrishnar** [comment]
@sonnyp thanks for the reply, I am developing an download manager extension for chrome. I tried making a file using the following command:
```sh
browserify index.js -o op.js
```

But when i tried to include it via script `<script src="op.js" type="text/javascript">` i couldn't find the `Aria2 ` object in the window.

**Comment by sonnyp** [comment]
If you want to use a global you need to use the standalone mode.

Something like 

```sh
browserify index.js -o Aria2.js -s Aria2
```

**Comment by sonnyp** [comment]
See https://github.com/browserify/browserify#usage

**Comment by gautamkrishnar** [comment]
Okay Thanks will check that 👍

**Comment by sonnyp** [comment]
I'll leave this open as a reminder to re-introduce the browser bundle

**Comment by gautamkrishnar** [comment]
👍 Thats great.

**Comment by gautamkrishnar** [comment]
@sonnyp any idea why you guys removed the browser bundle?

**Comment by ChiaYen-Kan** [comment]
Hi @sonnyp
i try build from current source code and use "bundle.js" in browser, but i got a error

```
bundle.js:519 Uncaught ReferenceError: global is not defined
    at new JSONRPCClient (bundle.js:519:22)
    at new Aria2 (bundle.js:706:3)
    at aria2.js.html:6:25
```

![bundle](https://user-images.githubusercontent.com/40080620/227120421-dce4da83-2d1e-4cde-8a91-3da1ccc7b368.png)

this is my test code

```
<html>
    <head>
        <meta charset="utf-8">
        <script type="application/javascript" src="bundle.js"></script>
        <script>
            var aria2 = new Aria2();
            aria2.call("addUri",
                ["https://fastly.picsum.photos/id/337/536/354.jpg?hmac=T7nJ4MjfcTPFuaaLRH_1zwqyOFzmldcV-f5abNr2MyE"],
            );
        </script>
    </head>
</html>
```

how to fix this error?

thank you

**Comment by pierrbt** [comment]
@ChiaYen-Kan, do you still want to make this work ? I've found a solution

**Comment by ChiaYen-Kan** [comment]
Hi @pierrbt 
i also have a solution, it's work, but i don't know is good solution or bad solution 🤔
following is my solution, base on https://github.com/sonnyp/aria2.js/commit/c960ebb1395cb08c51ec5a796b03f5609a92f459 in main branch

```
From 26b51a31699d3fd299dafe6566f3c79480301286 Mon Sep 17 00:00:00 2001
From: ChiaYen Kan <***>
Date: Fri, 24 Mar 2023 16:37:03 +0800
Subject: [PATCH] fix can't run in browser

---
 src/JSONRPCClient.js | 4 +++-
 1 file changed, 3 insertions(+), 1 deletion(-)

diff --git a/src/JSONRPCClient.js b/src/JSONRPCClient.js
index 8bab3aa..059babc 100644
--- a/src/JSONRPCClient.js
+++ b/src/JSONRPCClient.js
@@ -4,6 +4,8 @@ import Deferred from "./Deferred.js";
 import promiseEvent from "./promiseEvent.js";
 import JSONRPCError from "./JSONRPCError.js";
 
+var global = global || globalThis;
+
 class JSONRPCClient extends EventEmitter {
   constructor(options) {
     super();
@@ -12,7 +14,7 @@ class JSONRPCClient extends EventEmitter {
 
     Object.assign(
       this,
-      { WebSocket: global.WebSocket, fetch: global.fetch.bind(this) },
+      { WebSocket: global.WebSocket, fetch: global.fetch.bind(global) },
       this.constructor.defaultOptions,
       options
     );
-- 
2.41.0.windows.3
```

thank you

**Comment by pierrbt** [comment]
@ChiaYen-Kan,
Personally, I've juste changed global to window, and added the events depencies.

**Comment by ChiaYen-Kan** [comment]
Hi @pierrbt 
i am not a web developer, i just want to it can work in my little project
may be someone can make it best
thank you

**Comment by sonnyp** [comment]
aria2 v5 on npm now includes the `bundle.js` file which you can include in the browser

See the docs.
